import React from "react";
import { FaReact, FaJava, FaPhp, FaDatabase, FaAndroid, FaGitAlt, FaHtml5, FaCss3Alt, FaJs, FaUsers, FaCamera, FaBluetooth, FaNetworkWired, FaFileAlt, FaSearch, FaShieldAlt, FaCube, FaLightbulb, FaPalette, FaUserFriends } from "react-icons/fa";
import { SiFirebase, SiWireshark, SiFigma, SiMysql, SiGoogleanalytics, SiBlender } from "react-icons/si";
import { MdSecurity, MdAnalytics, MdBrush, MdGroup, MdSettings, MdStorage, MdApi } from "react-icons/md";
import { HiOutlineDocumentText, HiOutlineUserGroup, HiOutlineLightBulb, HiOutlineCamera, HiOutlineWifi } from "react-icons/hi";

export const getIconForTech = (tech: string): JSX.Element => {
  const iconMap: { [key: string]: JSX.Element } = {
    "Figma": <SiFigma className="text-[#F24E1E]" />,
    "PHP": <FaPhp className="text-[#777BB4]" />,
    "MySQL": <SiMysql className="text-[#4479A1]" />,
    "JavaScript": <FaJs className="text-[#F7DF1E]" />,
    "HTML/CSS": <FaHtml5 className="text-[#E34F26]" />,
    "Java": <FaJava className="text-[#ED8B00]" />,
    "Android Studio": <FaAndroid className="text-[#3DDC84]" />,
    "Firebase": <SiFirebase className="text-[#FFCA28]" />,
    "Wireshark": <SiWireshark className="text-[#1679A7]" />,
    "React": <FaReact className="text-[#61DAFB]" />,
    "Google Analytics": <SiGoogleanalytics className="text-[#E37400]" />,
    "User Research": <FaUsers className="text-[#4285F4]" />,
    "Wireframing": <HiOutlineDocumentText className="text-[#6366F1]" />,
    "Prototyping": <MdBrush className="text-[#EC4899]" />,
    "Design Thinking": <HiOutlineLightBulb className="text-[#8B5CF6]" />,
    "UX Research": <FaSearch className="text-[#059669]" />,
    "Persona Development": <HiOutlineUserGroup className="text-[#8B5CF6]" />,
    "AJAX": <MdApi className="text-[#F59E0B]" />,
    "Session Management": <MdSettings className="text-[#6B7280]" />,
    "SensorManager": <MdAnalytics className="text-[#10B981]" />,
    "Camera API": <FaCamera className="text-[#EF4444]" />,
    "Bluetooth API": <FaBluetooth className="text-[#3B82F6]" />,
    "Real-time Database": <MdStorage className="text-[#FFCA28]" />,
    "Network Miner": <FaNetworkWired className="text-[#1679A7]" />,
    "PCAP Analysis": <MdAnalytics className="text-[#059669]" />,
    "File Recovery Tools": <FaFileAlt className="text-[#F97316]" />,
    "Log Analysis": <FaSearch className="text-[#7C3AED]" />,
    "Incident Response": <MdSecurity className="text-[#DC2626]" />,
    "3D Modeling Software": <FaCube className="text-[#F97316]" />,
    "Animation Tools": <SiBlender className="text-[#F5792A]" />,
    "Lighting Systems": <FaLightbulb className="text-[#FCD34D]" />,
    "Texture Mapping": <FaPalette className="text-[#EC4899]" />,
    "Team Collaboration": <FaUserFriends className="text-[#10B981]" />,
    "Project Management": <MdSettings className="text-[#6366F1]" />,
    "Educational Planning": <HiOutlineDocumentText className="text-[#8B5CF6]" />,
    "Community Outreach": <FaUsers className="text-[#059669]" />,
    "Interactive Learning": <HiOutlineLightBulb className="text-[#F59E0B]" />,
    "Environmental Education": <HiOutlineLightBulb className="text-[#10B981]" />,
    "Marketing Strategy": <MdAnalytics className="text-[#EF4444]" />,
    "Brand Development": <MdBrush className="text-[#EC4899]" />,
    "Digital Marketing": <FaNetworkWired className="text-[#3B82F6]" />,
    "Customer Engagement": <FaUsers className="text-[#F59E0B]" />,
    "Sales Analytics": <MdAnalytics className="text-[#10B981]" />,
    "Team Leadership": <FaUserFriends className="text-[#8B5CF6]" />,
    "TypeScript": <FaJs className="text-[#3178C6]" />,
    "Tailwind CSS": <FaCss3Alt className="text-[#06B6D4]" />,
    "Interactive Visualization": <MdAnalytics className="text-[#8B5CF6]" />,
    "ISO/IEC 27005": <FaShieldAlt className="text-[#DC2626]" />,
    "Risk Assessment Framework": <MdSecurity className="text-[#EF4444]" />,
    "Cybersecurity Standards": <FaShieldAlt className="text-[#059669]" />,
    "Node.js": <FaJs className="text-[#339933]" />,
    "Express.js": <FaJs className="text-[#000000]" />,
    "MongoDB": <FaDatabase className="text-[#47A248]" />,
    "Socket.io": <FaNetworkWired className="text-[#010101]" />,
    "JWT Authentication": <FaShieldAlt className="text-[#000000]" />,
    "Recharts": <MdAnalytics className="text-[#8884D8]" />,
    "Healthcare APIs": <MdApi className="text-[#FF6B6B]" />,
    "Redux Toolkit": <FaReact className="text-[#764ABC]" />,
    "Radix UI": <FaReact className="text-[#161618]" />,
    "Framer Motion": <MdBrush className="text-[#0055FF]" />
  };
  
  return iconMap[tech] || <div className="w-3 h-3 bg-gray-600 rounded-sm"></div>;
};